#!/usr/bin/env ansible-playbook

- name: build configs
  hosts: localhost
  roles:
    - sflow_build
    - bird_build
    - eos_build
  tags:
    - build

- name: push bird config
  hosts: bird
  roles:
    - bird_push
  tags:
    - push
    - bird_push

- name: push sflow config
  hosts: sflow
  roles:
    - sflow_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - sflow_push

- name: push eos config
  hosts: eos
  roles:
    - eos_push
  vars:
    ansible_user: root
  tags:
    - push
    - eos_push
