#!/usr/bin/env ansible-playbook

- name: build sflow meta.yml
  hosts: localhost
  roles:
    - sflow_build
  tags:
    - build
    - sflow_build
    - sflow

- name: build bird.conf
  hosts: localhost
  roles:
    - bird_build
  tags:
    - build
    - bird_build
    - bird

- name: build eos config
  hosts: localhost
  roles:
    - eos_build
  tags:
    - build
    - eos_build
    - eos

- name: push sflow config
  hosts: sflow
  roles:
    - sflow_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - sflow_push
    - sflow

- name: push bird config
  hosts: bird
  serial: 1
  any_errors_fatal: true
  roles:
    - bird_push
  tags:
    - push
    - bird_push
    - bird

- name: push eos config
  hosts: eos
  serial: 1
  any_errors_fatal: true
  roles:
    - eos_push
  vars:
    ansible_user: root
  tags:
    - push
    - eos_push
    - eos
