#!/usr/bin/env ansible-playbook

- name: build sflow meta.yml
  hosts: localhost
  roles:
    - sflow_build
  tags:
    - build
    - build_sflow
    - sflow

- name: build bird.conf
  hosts: localhost
  roles:
    - bird_build
  tags:
    - build
    - build_bird
    - bird

- name: build eos config
  hosts: localhost
  roles:
    - eos_build
  tags:
    - build
    - build_eos
    - eos

- name: push sflow config
  hosts: sflow
  roles:
    - sflow_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - push_sflow
    - sflow

- name: push bird config
  hosts: bird
  roles:
    - bird_push
  tags:
    - push
    - push_bird
    - bird

- name: push eos config
  hosts: eos
  roles:
    - eos_push
  vars:
    ansible_user: root
  tags:
    - push
    - push_eos
    - eos
