- name: reconfigure eos
  block:
    - name: retrieve current config
      arista.eos.eos_command:
        commands:
          - show running-config
      register: running_config

    - name: retrieve startup config
      arista.eos.eos_command:
        commands:
          - show startup-config
      register: startup_config

    - name: test for pending changes
      ansible.utils.fact_diff:
        before: '{{ startup_config.stdout_lines[0]|reject("match", "^(!|\s*$)") }}'
        after: '{{ running_config.stdout_lines[0]|reject("match", "^(!|$)") }}'
      register: config_diff

    - name: replace running config
      arista.eos.eos_command:
        commands:
          - write memory
      when: config_diff.changed
      changed_when: true
      notify: notify about eos save
  rescue:
    - name: notify about eos failure
      ansible.builtin.uri:
        url: "{{ secrets.matrix.alerts_room_url }}"
        method: POST
        body_format: json
        body:
          msgtype: m.text
          format: org.matrix.custom.html
          body: |
            ❌ **EOS Failed at {{ inventory_hostname_short }}**

            Error while {{ ansible_failed_task.name }}:
              {{ ansible_failed_result.msg|indent(2) }}
          formatted_body: |
            <h1>❌ EOS Failed at <code>{{ inventory_hostname_short }}</code></h1>
            <ul>
              <li>Error while {{ ansible_failed_task.name }}:
                <pre>{{ ansible_failed_result.msg|e }}</pre>
              </li>
            </ul>
        follow_redirects: no
      delegate_to: localhost
      when: secrets.matrix.alerts_room_url is defined

    - name: stop on error
      ansible.builtin.fail:
